apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-metricbeat" .Chart.Name }}
  labels:
    k8s-app: {{ printf "%s-metricbeat" .Chart.Name }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ printf "%s-metricbeat" .Chart.Name }}
  labels:
    k8s-app: {{ printf "%s-metricbeat" .Chart.Name }}
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  - events
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources:
  - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
  - statefulsets
  - deployments
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-metricbeat" .Chart.Name }}
subjects:
- kind: ServiceAccount
  name: {{ printf "%s-metricbeat" .Chart.Name }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ printf "%s-metricbeat" .Chart.Name }}
  apiGroup: rbac.authorization.k8s.io
