# Deploy a Metricbeat instance per node for node metrics retrieval
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ printf "%s-metricbeat" .Chart.Name }}
  labels:
    k8s-app: {{ printf "%s-metricbeat" .Chart.Name }}
spec:
  template:
    metadata:
      labels:
        k8s-app: {{ printf "%s-metricbeat" .Chart.Name }}
    spec:
      serviceAccountName: {{ printf "%s-metricbeat" .Chart.Name }}
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: metricbeat
        image: docker.elastic.co/beats/metricbeat:6.3.2
        args: [
          "-c", "/etc/metricbeat.yml",
          "-e",
          "-system.hostfs=/hostfs",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/metricbeat.yml
          readOnly: true
          subPath: metricbeat.yml
        - name: modules
          mountPath: /usr/share/metricbeat/modules.d
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: proc
          mountPath: /hostfs/proc
          readOnly: true
        - name: cgroup
          mountPath: /hostfs/sys/fs/cgroup
          readOnly: true
        - name: root-ca
          mountPath: /etc/pki/root/root-ca.pem
          readOnly: true
          subPath: root-ca.pem
      volumes:
      - name: proc
        hostPath:
          path: /proc
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ printf "%s-daemonset-config" .Chart.Name }}
      - name: modules
        configMap:
          defaultMode: 0600
          name: {{ printf "%s-daemonset-modules" .Chart.Name }}
      - name: data
        hostPath:
          path: /var/lib/metricbeat-data
          type: DirectoryOrCreate
      - name: root-ca
        configMap:
          name: {{ printf "%s-metricbeat-root-ca" .Chart.Name }}

