apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-metricbeat-de-config" .Chart.Name }}
  labels:
    k8s-app: {{ printf "%s-metricbeat-config" .Chart.Name }}
data:
  metricbeat.yml: |-
    metricbeat.modules:
    # State metrics from kube-state-metrics service:
    - module: kubernetes
      enabled: true
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_statefulset
        - state_pod
        - state_container
      period: 10s
      hosts: ["{{ template "kube-state-metrics.fullname" . }}:{{ .Values.service.port }}"]

    output.elasticsearch:
      hosts: {{ pluck .Values.global.env .Values.es.hosts | first | default .Values.es.hosts._default }}
      username: {{ pluck .Values.global.env .Values.es.username | first | default .Values.es.username._default }}
      password: {{ pluck .Values.global.env .Values.es.password | first | default .Values.es.password._default }}
      ssl.certificate_authorities: ["/etc/pki/root/root-ca.pem"]

    xpack.monitoring:
      enabled: true
      elasticsearch:
        username: {{ pluck .Values.global.env .Values.es.monusername | first | default .Values.es.monusername._default }}
        password: {{ pluck .Values.global.env .Values.es.monpassword | first | default .Values.es.monpassword._default }}
        ssl.certificate_authorities: ["/etc/pki/root/root-ca.pem"]
