apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis-cluster
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: redis-cluster
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: redis-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: redis-cluster
subjects:
- kind: ServiceAccount
  name: redis-cluster
