---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: {{ .Values.namespace }}
spec:
  selector:
    component: clickhouse
  ports:
  - name: http
    port: 8123
    targetPort: 8123
    protocol: TCP
  - name: native
    port: 9000
    targetPort: 9000
    protocol: TCP
