nodeSelector:
  kops.k8s.io/instancegroup: systemnodes
tolerations:
- effect: NoExecute
  key: dedicated
  operator: Equal
  value: systemnodes
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  fqdn: "grafana.base.domain"
  tls:
  - hosts:
    - grafana.base.domain
    secretName: grafana-tls
extraVars:
- name: GF_INSTALL_PLUGINS
  value: grafana-worldmap-panel,vertamedia-clickhouse-datasource
