---
kind: ConfigMap
apiVersion: v1
metadata:
  name: loghouse-user-config
  namespace: {{ .Values.namespace }}
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
data:
  user.conf: |-
    admin:
      - ".*"
