apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
{{- if ne .Values.environment "production" }}
    nginx.ingress.kubernetes.io/auth-type: "basic"
    nginx.ingress.kubernetes.io/auth-secret: "ingress-basic-auth-common"
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - tech2"
    kubernetes.io/tls-acme: "true"
{{- end }}
spec:
{{- if ne .Values.environment "production" }}
  tls:
  - hosts:
    - {{ pluck .Values.environment .Values.domains | first | default .Values.domains._default | quote }}
    secretName: front-tls
{{- end }}
  rules:
  - host: {{ pluck .Values.environment .Values.domains | first | default .Values.domains._default | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: front
          servicePort: 9155
{{- if eq .Values.environment "production" }}
  - host: {{ pluck .Values.environment .Values.domains | first | default .Values.domains._default | printf "www.%s" | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: front
          servicePort: 9155
{{- end }}    
